[package]
name = "pkgar-keys"
version = "0.1.13"
description = "Key management tool/library for pkgar"
license = "MIT"
authors = ["Wesley Hershberger <mggmugginsmc@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/pkgar"
readme = "README.md"
edition = "2018"

[dependencies]
clap = "2.33.3"
dirs = "3.0.1"
error-chain = "0.12"
hex = { version = "0.4.2", features = ["serde"] }
lazy_static = "1.4.0"
seckey = "0.11.2"
serde = { version = "=1.0.197", default_features = false, features = ["derive"] }
sodiumoxide = { version = "0.2.7", default_features = false }
termion = "3"
#thiserror = "1.0.20"
toml = "0.8"
user-error = "1.2.8"
