[package]
name = "pkgar-repo"
version = "0.1.0"
description = "Redox Package Repository"
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/pkgar"
edition = "2018"

[dependencies]
pkgar = { version = "0.1.7", path = "../pkgar" }
pkgar-core = { version = "0.1.0", path = "../pkgar-core" }
reqwest = { version = "0.11.10", default_features = false, features = ["blocking", "rustls-tls"] }
sodiumoxide = { version = "=0.2.6", default_features = false }
